### ISSUE TITLE
Clicking outerContainer after collapsing custom-scroll gains negative scrollValue

### ISSUE THREAD

**Issue by yinonc** [rommguy/react-custom-scroll#65] opened 2019-04-07 15:12 UTC
Hey,
There's a problematic scenario when custom-scroll is collapsed and then re-renders:
**Flow**:
1. Open some component with `react-custom-scroll`.
2. Collapse it with some components so no scroll can be performed (accordion etc..)
3. Un-collapse it.
4. Click on bottom and top of the outer container.

**Result**: the scroll jumps (scrollPos gains value 0).
That's because the calculated scroll top is negative.

PR for fix: https://github.com/rommguy/react-custom-scroll/pull/64

**Comment by taksenov** [comment] 2019-06-18 16:34
Hi @rommguy. you repository "react-custom-scroll" is awesome!

But some times ago we found one trouble in the our project, like as in this PR
https://github.com/rommguy/react-custom-scroll/pull/64

Can you please saw this PR https://github.com/rommguy/react-custom-scroll/pull/64 ?  And if code is correct, may you merged this PR and update version of the "react-custom-scroll"?

Sorry for my english. 

Thank you.

**Closed** 2019-06-23 12:39 UTC

**Comment by rommguy** [comment] 2019-06-23 12:48
@yinonc Thank you for the PR. I didn't merge it because I wanted to find the reason for the problem and add a failing test before fixing the issue. 
Eventually I think I found the cause to be the function setCustomScrollbarRef. The bug was that when the customScrollbar ref is changed, the component kept the old instance which was stale after scroll state was changed. This resulted in wrong calculation for click position, when checking if the click is on the custom scrollbar or not.

I deployed this fix in version 4.0.3
@taksenov and @yinonc, I would appreciate it if you could verify this change fixed the problem and if not let me know
Thank you for using this component and for opening the issue

**Comment by rommguy** [comment] 2019-06-23 13:07
duplicates #53

**Comment by taksenov** [comment] 2019-06-24 07:18
@rommguy Thank you, version 4.0.3 solved our problem
